### ISSUE TITLE
Error message with DHI MIKE 2019

### ISSUE THREAD

**Issue by CoastalKW** [pwcazenave/dhi-toolbox#2]
I receive the following error message when running the code (I'm using MATLAB 2019b and DHI MIKE 2019):
"Error using netcdflib
The NetCDF library encountered an error during execution of 'open' function - 'Unknown
file format (NC_ENOTNC)'.

Error in netcdf.open (line 67)
        [varargout{:}] = netcdflib ( 'open', filename, varargin{1} );

Error in internal.matlab.imagesci.nc/openToRead (line 1278)
            this.ncRootid = netcdf.open(this.Filename,'NOWRITE');

Error in internal.matlab.imagesci.nc (line 121)
                    this.openToRead();

Error in ncread (line 61)
ncObj   = internal.matlab.imagesci.nc(ncFile);

Error in getRoughness (line 122)
    zBathy = abs(double(ncread(bathyFile, 'Bathymetry')));"

**Comment by pwcazenave** [comment]
Apologies, it's been a long time since I used this library (or in fact MATLAB), so I'm not really able to help figure out what's wrong here. Hope you managed to get it sorted!
